config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index, :show]
  resources :batters, except: :destroy
  resources :pitchers, except: :destroy
  resources :plate_appearances, except: :destroy
  get '/main', to: 'plate_appearances#main', as: 'main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pitcher.rb
class Pitcher < ApplicationRecord
    has_many :plate_appearances
    belongs_to :team, class_name: "Team", foreign_key: :api_team_id
end

app/controllers/pitchers_controller.rb
class PitchersController < ApplicationController
  def index
    @pitchers = Pitcher.all
  end

  def show
    @pitcher = Pitcher.find(params[:id])
  end

  def new
    @pitcher = Pitcher.new
  end

  def edit
    @pitcher = Pitcher.find(params[:id])
  end

  def create
    @pitcher = Pitcher.create(pitcher_params(:name, :tier))
    redirect_to pitcher_path(@pitcher)
  end

  def update
    @pitcher = Pitcher.find(params[:id])
    @pitcher.update(pitcher_params(:name, :tier))
    redirect_to pitcher_path(@pitcher)
  end


  private

  def pitcher_params(*args)
    params.require(:pitcher).permit(*args)
  end

end

app/views/pitchers/_form.erb
<%= form_for @pitcher do |f|%>
    <p><%= f.label 'Pitcher Name:'%></p>
    <%= f.text_field :name %><br>

    <p><%= f.label 'Pitcher Tier:'%></p>
    <%= f.number_field :tier, min: 1, max: 4%><br><br>

    <%= f.submit %>

<%end%>

app/views/pitchers/edit.html.erb
<h1>Update Pitcher</h1>
<%= render 'form %>

app/views/pitchers/index.html.erb
<h1>Pitchers</h1>
<%@pitchers.each do |pitcher|%>
    <p><%= link_to pitcher.name, pitcher_path(pitcher)%>, Tier: <%= pitcher.tier %></p>
<%end%>
<%= link_to "Create a new pitcher", new_pitcher_path%>

app/views/pitchers/new.html.erb
<h1>Create Pitcher</h1>
<%= render 'form' %>

app/views/pitchers/show.html.erb
<h1><%= @pitcher.name%></h1>
    <div>ERA: <%= @pitcher.era %></div>
    <div>Wins: <%= @pitcher.w %></div>
    <div>Losses: <%= @pitcher.l %></div>
    <div>Strikeouts: <%= @pitcher.so %></div>
    <div>Walks: <%= @pitcher.bb %></div>


<p><%= link_to "Edit Pitcher", edit_pitcher_path %></p>
<p><%= link_to "See All", pitchers_path %></p>
<%= link_to 'Main Menu', main_path %>