config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index, :show]
  resources :batters, except: :destroy
  resources :pitchers, except: :destroy
  resources :plate_appearances, except: :destroy
  get '/main', to: 'plate_appearances#main', as: 'main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/batter.rb
class Batter < ApplicationRecord
    has_many :plate_appearances
    belongs_to :team, class_name: "Team", foreign_key: :api_team_id

    def average
        remove_leading_zero(self.avg)
    end

    def on_base_percentage
        remove_leading_zero(self.obp)
    end

    def slugging_percentage
        remove_leading_zero(self.slg)
    end

    def on_base_plus_slugging_percentage
        remove_leading_zero(self.ops)
    end

    def remove_leading_zero(stat)
        stat.to_s.sub!(/^0/, "")
    end
end

app/controllers/batters_controller.rb
class BattersController < ApplicationController
  def index
    @batters = Batter.all
  end

  def show
    @batter = Batter.find(params[:id])
  end

  def new
    @batter = Batter.new
  end

  def edit
    @batter = Batter.find(params[:id])
  end

  def create
    @batter = Batter.create(batter_params(:name, :tier))
    redirect_to batter_path(@batter)
  end

  def update
    @batter = Batter.find(params[:id])
    @batter.update(batter_params(:name, :tier))
    redirect_to batter_path(@batter)
  end


  private

  def batter_params(*args)
    params.require(:batter).permit(*args)
  end

end

app/views/batters/_form.erb
<%= form_for @batter do |f|%>
    <p><%= f.label 'Batter Team:'%></p>
    <%= f.collection_select(:team_id, Team.all, :id, :name) %><br>

    <p><%= f.label 'Batter Name:'%></p>
    <%= f.text_field :name %><br>

    <p><%= f.label 'Batter Tier:'%></p>
    <%= f.number_field :tier, min: 1, max: 4%><br><br>

    <%= f.submit %>

<%end%>

app/views/batters/edit.html.erb
<h1>Update Batter</h1>
<%= render "form" %>

app/views/batters/index.html.erb
<h1>Batters</h1>
<%@batters.each do |batter|%>
    <p><%= link_to batter.name, batter_path(batter)%>, Tier: <%= batter.tier %></p>
<%end%>
<%= link_to "Create a new batter", new_batter_path%>
<%= link_to 'Main Menu', main_path %>

app/views/batters/new.html.erb
<h1>Create a Batter</h1>
<%= render 'form' %>

app/views/batters/show.html.erb
<h1><%= @batter.name%></h1>
    <div>AVG: <%= @batter.average %></div>
    <div>OBP: <%= @batter.on_base_percentage %></div>
    <div>SLG: <%= @batter.slugging_percentage %></div>
    <div>OPS: <%= @batter.on_base_plus_slugging_percentage %></div>
    <div>Home Runs: <%= @batter.hr %></div>
    <div>Strikeouts: <%= @batter.so %></div>
    <div>Walks: <%= @batter.bb %></div>
<p><%= link_to "Edit Batter", edit_batter_path %></p>
<p><%= link_to "See All", batters_path %></p>
<%= link_to 'Main Menu', main_path %>