config/routes.rb
Rails.application.routes.draw do
  resources :teams, only: [:index, :show]
  resources :batters, except: :destroy
  resources :pitchers, except: :destroy
  resources :plate_appearances, except: :destroy
  get '/main', to: 'plate_appearances#main', as: 'main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plate_appearance.rb
class PlateAppearance < ApplicationRecord
    belongs_to :batter
    belongs_to :pitcher

    def pset 
        {
        bb: 85,
        hbp: 95,
        single: 234,
        double: 279,
        triple: 285,
        homerun: 319,
        lineout: 413,
        groundout: 606,
        flyout: 771,
        k: 1000
        }
    end
    
    def outcome
        rand = rand(1000)
        pset.reject {|k, v| rand > v }.min_by {|k,v|v}.first.upcase
    end

    def on_base?
        odds_b = @batter.obp / (@batter.obp - 1) * -1
        odds_p = @pitcher.obp / (@pitcher.obp - 1) * -1
        odds = (odds_b * odds_p)
end

app/controllers/plate_appearances_controller.rb
class PlateAppearancesController < ApplicationController
  def index
    @plate_appearances = PlateAppearance.all
  end

  def main
  end

  def show
    @plate_appearance = PlateAppearance.find(params[:id])
    @outcome = @plate_appearance.outcome
  end

  def new
    @plate_appearance = PlateAppearance.new
  end

  def edit
    @plate_appearance = PlateAppearance.find(params[:id])
  end

  def create
    @plate_appearance = PlateAppearance.create(plate_appearance_params(:batter_id, :pitcher_id))
    redirect_to plate_appearance_path(@plate_appearance)
  end

  def update
    @plate_appearance = PlateAppearance.find(params[:id])
    @plate_appearance.update(plate_appearance_params(:batter_id, :pitcher_id))
    redirect_to plate_appearance_path(@plate_appearance)
  end


  private

  def plate_appearance_params(*args)
    params.require(:plate_appearance).permit(*args)
  end

end

app/views/plate_appearances/edit.html.erb
<h1>Plate Appearance Simulator</h1>
<%= form_for @plate_appearance do |f| %>
    <h3><%= f.label 'Batter:'%></h3>
    <%= f.collection_select(:batter_id, Batter.all, :id, :name) %>

    <h3><%= f.label 'Pitcher:'%></h3>
    <%= f.collection_select(:pitcher_id, Pitcher.all, :id, :name) %>

    <%= f.submit 'Simulate At-Bat'%>
<%end%> 

app/views/plate_appearances/index.html.erb
<h1>All Plate Appearances</h1>
<% @plate_appearances.each do |pa| %>
    <p><%= pa.batter.name %> vs. <%= pa.pitcher.name%>: <%= pa.outcome%>.</p>
<%end%>
<%= link_to 'Main Menu', main_path %>
 

app/views/plate_appearances/main.erb
<h1>At-Bat Simulator</h1>
<%= link_to 'Create A Batter', new_batter_path %><br>
<%= link_to 'Create A Pitcher', new_pitcher_path %><br>
<%= link_to 'See All Teams', teams_path %><br>
<%= link_to 'Simulate an At-Bat', new_plate_appearance_path %>

app/views/plate_appearances/new.html.erb
<h1>Plate Appearance Simulator</h1>
<%= form_for @plate_appearance do |f| %>
    
    <%= f.label 'Batter:'%>
    <%= f.collection_select(:batter_id, Batter.all, :id, :name) %> 

    <br>
    <%= f.label 'Pitcher:'%>
    <%= f.collection_select(:pitcher_id, Pitcher.all, :id, :name) %>
    <br>
    <br>
    <%= f.submit 'Simulate At-Bat'%>
<%end%> 
<br>
<%= link_to 'Main Menu', main_path %>

app/views/plate_appearances/show.html.erb
<h1>Outcome: <%= @outcome %></h1>
<p><%= @plate_appearance.batter.name %> vs. <%= @plate_appearance.pitcher.name%>: <%= @outcome %>.</p>
<%= link_to "All Plate Appearances", plate_appearances_path%>
<br>
<%= link_to 'Main Menu', main_path %>